groups:
  - name: targets
    rules:
      - alert: monitor_service_down
        expr: up == 0
        labels:
          severity: critical
        annotations:
          summary: "Monitor service non-operational"
          description: "Service {{ $labels.instance }} is down."

      - alert: code_404
        expr: sum(nginx_vts_server_requests_total{code="4xx", host="*"}) by (instance) > 0
        labels:
          severity: critical
        annotations:
          summary: "Nginx returned 404"
          description: "Service return 404 {{ $value }} times for instance {{ $labels.instance }}."
